version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - POSTGRES_PASSWORD=12345  # Define a senha do PostgreSQL para o superusuário

  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=12345  # Define a mesma senha para o PostgreSQL
